learn_makefile: learn_makefile.o printfunc.o
	cc -o learn_makefile learn_makefile.o printfunc.o

learn_makefile.o: learn_makefile.c
	cc -c learn_makefile.c

printfunc.o: printfunc.c
	cc -c printfunc.c
